apiversion: apps/v1
kind: Deployment
metadata:
  name: testing-mern-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testing-mern-worker
  template:
    metadata:
      labels:
        app: testing-mern-worker
    spec:
      containers:
        - name: testing-mern-worker
          image:  ogadityahota/testing-mern-worker:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
            - containerPort: 8081
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 128Mi
          secret:
            secretName: testing-mern-worker-secret