apiversion: v1
kind: Secret
metadata:
  name: testing-mern-worker-secret
type: Opaque
data:
  .evn: UE9SVD0zMDAyCldTX1BPUlQ9ODA4MQpEQVRBQkFTRV9VUkw9cG9zdGdyZXM6Ly9wb3N0Z3JlczphZG1pbjEyM0Bsb2NhbGhvc3Q6NTQzMi9wb3N0Z3Jlcwpmcm9udGVuZD1odHRwOi8vbG9jYWxob3N0OjUxNzMKYmFja2VuZD1odHRwOi8vbG9jYWxob3N0OjMwMDEKd29ya2VyPWh0dHA6Ly9sb2NhbGhvc3Q6MzAwMgp3b3JrZXIyPWh0dHA6Ly9sb2NhbGhvc3Q6MzAwMwp3b3JrZXJfV1M9d3M6Ly9sb2NhbGhvc3Q6ODA4MQp3b3JrZXIyX1dTPXdzOi8vbG9jYWxob3N0OjgwODIKUkVESVNfVVJMPXJlZGlzOi8vcmVkaXM6NjM3OQo=

  