apiversion: v1
kind: Service
metadata:
  name: testing-mern-worker-service
spec:
  selector:
    app: testing-mern-worker
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3002
    - name: ws
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP