apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testing-mern-ingress
  namespace: default
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: testing-mern.adityahota.online
    http:
      paths:
      - path: /backend
        pathType: Prefix
        backend:
          service:
            name: testing-mern-backend-service
            port:
              number: 3001
      - path: /worker
        pathType: Prefix
        backend:
          service:
            name: testing-mern-worker-service
            port:
              number: 3002
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: testing-mern-worker-service
            port:
              number: 8081