apiVersion: v1
kind: Secret
metadata:
  name: testing-mern-backend-secret
type: Opaque
stringData:
  PORT: 3001
  DATABASE_URL: postgresql://neondb_owner:npg_BK1mWS0oaLGz@ep-rapid-hat-a4ostuob-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
  frontend: "http://localhost:5173"
  backend: "http://localhost:3001"
  worker: "http://localhost:3002"
  worker2: "http://localhost:3003"
  worker_WS: "ws://localhost:8081"
  worker2_WS: "ws://localhost:8082"
