apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing-mern-worker
  labels:
    app: testing-mern-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testing-mern-worker
  template:
    metadata:
      labels:
        app: testing-mern-worker
    spec:
      containers:
        - name: testing-mern-worker
          image: ogadityahota/testing-mern-worker:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002   
            - containerPort: 8081   
          resources:
            limits:
              cpu: "500m"
              memory: "500Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          envFrom:
            - secretRef:
                name: testing-mern-worker-secret
---
apiVersion: v1
kind: Service
metadata:
  name: testing-mern-worker-service
  labels:
    app: testing-mern-worker
spec:
  selector:
    app: testing-mern-worker
  ports:
    - name: http
      protocol: TCP
      port: 3002
      targetPort: 3002
    - name: ws
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
