apiVersion: v1
kind: Secret
metadata:
  name: testing-mern-worker-secret
type: Opaque
stringData:
  PORT: "3002"
  WS_PORT: "8081"
  DATABASE_URL: "postgres://postgres:admin123@localhost:5432/postgres"
  frontend: "http://localhost:5173"
  backend: "http://localhost:3001"
  worker: "http://localhost:3002"
  worker2: "http://localhost:3003"
  worker_WS: "ws://localhost:8081"
  worker2_WS: "ws://localhost:8082"
  REDIS_URL: "redis://redis.default.svc.cluster.local:6379"
