apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-sm-store
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secrets-manager-creds
            key: accessKeyId
          secretAccessKeySecretRef:
            name: aws-secrets-manager-creds
            key: secretAccessKey
