apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: testing-mern-worker-external
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-sm-store
  target:
    name: testing-mern-worker-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: prod-worker-testing-mern
