apiversion: apps/v1
kind: Deployment
metadata:
  name: testing-mern-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testing-mern-backend
  template:
    metadata:
      labels:
        app: testing-mern-backend
    spec:
      containers:
        - name: testing-mern-backend
          image:  ogadityahota/testing-mern-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 128Mi
          secret:
            secretName: testing-mern-backend-secret