apiversion: v1
kind: Secret
metadata:
  name: testing-mern-backend-secret
type: Opaque
data:
  .evn: UE9SVD0zMDAxCkRBVEFCQVNFX1VSTD1wb3N0Z3Jlc3FsOi8vbmVvbmRiX293bmVyOm5wZ19CSzFtV1Mwb2FMR3pAZXAtcmFwaWQtaGF0LWE0b3N0dW9iLXBvb2xlci51cy1lYXN0LTEuYXdzLm5lb24udGVjaC9uZW9uZGI/c3NsbW9kZT1yZXF1aXJlJmNoYW5uZWxfYmluZGluZz1yZXF1aXJlCmZyb250ZW5kPWh0dHA6Ly9sb2NhbGhvc3Q6NTE3MwpiYWNrZW5kPWh0dHA6Ly9sb2NhbGhvc3Q6MzAwMQp3b3JrZXI9aHR0cDovL2xvY2FsaG9zdDozMDAyCndvcmtlcjI9aHR0cDovL2xvY2FsaG9zdDozMDAzCndvcmtlcl9XUz13czovL2xvY2FsaG9zdDo4MDgxCndvcmtlcjJfV1M9d3M6Ly9sb2NhbGhvc3Q6ODA4Mgo=
  