apiversion: v1
kind: Service
metadata:
  name: testing-mern-backend-service
spec:
  selector:
    app: testing-mern-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP