services:
  redis:
    image: redis:7-alpine
    container_name: redis-worker-one
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bun-worker-one
    ports:
      - "3002:3002"
      - "8081:8081"
    env_file:
      - .env
    environment:
      PORT: ${PORT}
      WS_PORT: ${WS_PORT}
      FRONTEND_URL: ${frontend}
      BACKEND_URL: ${backend}
      WORKER_URL: ${worker}
      REDIS_URL: ${REDIS_URL}
      
    restart: unless-stopped
